extract_embeddings:
  MODEL_FOLDER: '~/chess_games/models/encoder_model.h5'
  STORE_EMBEDDINGS_PATH: '~/chess_games/embeddings'
  REFERENCE_EMBEDDINGS: '~/chess_games/embeddings/x_ref_embeddings_autov3.pkl'
  REPORT_PATH: '~/chess_games/drift_reports'
  ML_FLOW_EXPERIMENT: 'Drift Analysis using embeddings'